
export const VerificationSteps = [
  { id: "01", label: "Upload Document" },
  { id: "02", label: "Hash Generated" },
  { id: "03", label: "Chain Queried" },
  { id: "04", label: "Proof Returned" },
];

export const mockPlayers = [
  {
    id: "1",
    rank: 1,
    previousRank: 2,
    name: "MoleKing",
    level: 24,
    points: 2456,
    avatar: "👑",
    wallet: "0x1234...5678",
    achievements: [
      { id: "1", name: "Crown Holder", description: "Reached #1 on leaderboard", icon: "👑", rarity: "legendary" },
      { id: "2", name: "Score Master", description: "Scored over 2000 points", icon: "🎯", rarity: "epic" },
      { id: "3", name: "Streak King", description: "10 game win streak", icon: "🔥", rarity: "rare" },
    ],
    streak: 12,
    gamesPlayed: 156,
    winRate: 78,
  },
  {
    id: "2",
    rank: 2,
    previousRank: 1,
    name: "WhackMaster",
    level: 22,
    points: 2189,
    avatar: "🎭",
    wallet: "0x8765...4321",
    achievements: [
      { id: "4", name: "Precision Pro", description: "High accuracy rate", icon: "🎯", rarity: "epic" },
      { id: "5", name: "Speed Demon", description: "Fast reaction times", icon: "⚡", rarity: "rare" },
    ],
    streak: 8,
    gamesPlayed: 134,
    winRate: 82,
  },
  {
    id: "3",
    rank: 3,
    previousRank: 3,
    name: "MoleMaster99",
    level: 20,
    points: 1987,
    avatar: "🔥",
    wallet: "0x9999...0000",
    achievements: [
      { id: "6", name: "Veteran", description: "100+ games played", icon: "🏆", rarity: "rare" },
      { id: "7", name: "Consistent", description: "Daily player for 30 days", icon: "📅", rarity: "common" },
    ],
    streak: 5,
    gamesPlayed: 198,
    winRate: 65,
  },
  {
    id: "4",
    rank: 4,
    previousRank: 5,
    name: "BlockChampion",
    level: 19,
    points: 1845,
    avatar: "💎",
    wallet: "0xaaaa...bbbb",
    achievements: [
      { id: "8", name: "Rising Star", description: "Climbed 5 ranks in a day", icon: "⭐", rarity: "rare" },
    ],
    streak: 3,
    gamesPlayed: 89,
    winRate: 71,
  },
  {
    id: "5",
    rank: 5,
    previousRank: 4,
    name: "StarkWhacker",
    level: 18,
    points: 1756,
    avatar: "🎮",
    wallet: "0xcccc...dddd",
    achievements: [
      { id: "9", name: "Newcomer", description: "First week completed", icon: "🌟", rarity: "common" },
    ],
    streak: 2,
    gamesPlayed: 67,
    winRate: 68,
  },
];
